development:
  adapter: mysql2
  database: chat-app
  hostname: localhost
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: chat-app
  hostname: localhost 
  username: root
  password: root
  pool: 5
  timeout: 5000
